[workspace]
authors = ["Scott Henderson <3924836+scottyhq@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "blog"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
serve='myst start --execute'
build='myst build --execute --html'
check-links='myst build --check-links'
spellcheck='codespell --skip  _build'

[dependencies]
mystmd = ">=1.5.0,<2"
xarray = ">=2025.6.1,<2026"
codespell = ">=2.4.1,<3"
jupytext = ">=1.17.2,<2"
jupyter_server = ">=2.16.0,<3"
ipykernel = ">=6.29.5,<7"
xproj = ">=0.2.0,<0.3"
xvec = ">=0.4.0,<0.5"
#odc-geo = ">=0.5.0rc1,<0.6"
rioxarray = ">=0.19.0,<0.20"
geopandas = ">=1.1.1,<2"
geodatasets = ">=2024.8.0,<2025"

[pypi-dependencies]
rasterix = ">=0.1a4, <0.1a5"
